// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dsh} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckUpdate():Promise<void>;

export function GetStatus():Promise<main.StatusPayload>;

export function OnLog(arg1:string):Promise<void>;

export function OnStatus(arg1:dsh.Status,arg2:string):Promise<void>;

export function OnURL(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RestartDSH():Promise<void>;

export function RetryBootstrap():Promise<void>;

export function StopDSH():Promise<void>;

export function WindowHideToTray():Promise<void>;

export function WindowMin():Promise<void>;

export function WindowToggleMax():Promise<void>;
