// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OnLog(arg1) {
  return window['go']['main']['App']['OnLog'](arg1);
}

export function OnStatus(arg1, arg2) {
  return window['go']['main']['App']['OnStatus'](arg1, arg2);
}

export function OnURL(arg1) {
  return window['go']['main']['App']['OnURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RestartDSH() {
  return window['go']['main']['App']['RestartDSH']();
}

export function RetryBootstrap() {
  return window['go']['main']['App']['RetryBootstrap']();
}

export function StopDSH() {
  return window['go']['main']['App']['StopDSH']();
}

export function WindowHideToTray() {
  return window['go']['main']['App']['WindowHideToTray']();
}

export function WindowMin() {
  return window['go']['main']['App']['WindowMin']();
}

export function WindowToggleMax() {
  return window['go']['main']['App']['WindowToggleMax']();
}
